# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from eurobot2019_messages/drop_motors.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class drop_motors(genpy.Message):
  _md5sum = "da232c9309df34c64bd87bc76c440433"
  _type = "eurobot2019_messages/drop_motors"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# The z position of the left stepper motor
float32 left_z
# The x position of the left pusher
float32 left_x
# The z position of the middle stepper motor
float32 middle_z
# The x position of the middle pusher
float32 middle_x
# The z position of the right stepper motor
float32 right_z
# The x position of the right pusher
float32 right_x
"""
  __slots__ = ['left_z','left_x','middle_z','middle_x','right_z','right_x']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_z,left_x,middle_z,middle_x,right_z,right_x

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(drop_motors, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.left_z is None:
        self.left_z = 0.
      if self.left_x is None:
        self.left_x = 0.
      if self.middle_z is None:
        self.middle_z = 0.
      if self.middle_x is None:
        self.middle_x = 0.
      if self.right_z is None:
        self.right_z = 0.
      if self.right_x is None:
        self.right_x = 0.
    else:
      self.left_z = 0.
      self.left_x = 0.
      self.middle_z = 0.
      self.middle_x = 0.
      self.right_z = 0.
      self.right_x = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.left_z, _x.left_x, _x.middle_z, _x.middle_x, _x.right_z, _x.right_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.left_z, _x.left_x, _x.middle_z, _x.middle_x, _x.right_z, _x.right_x,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.left_z, _x.left_x, _x.middle_z, _x.middle_x, _x.right_z, _x.right_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.left_z, _x.left_x, _x.middle_z, _x.middle_x, _x.right_z, _x.right_x,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
