# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from eurobot2019_messages/pickup.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class pickup(genpy.Message):
  _md5sum = "fc43b8165e5ce088844c3951cd1006fd"
  _type = "eurobot2019_messages/pickup"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Is the target puck vertical?
bool is_vertical

# Have we reached the correct position yet?
# Note that the picker will be told to open up and get to the right z
# Before continuing by setting this to false
bool pos_reached

# 0 is "idle at bottom front"
# 1 is red
# 2 is green
# 3 is blue
# 4 is gold
# 5 is "idle at top back"
uint8 colour
"""
  __slots__ = ['is_vertical','pos_reached','colour']
  _slot_types = ['bool','bool','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       is_vertical,pos_reached,colour

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(pickup, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.is_vertical is None:
        self.is_vertical = False
      if self.pos_reached is None:
        self.pos_reached = False
      if self.colour is None:
        self.colour = 0
    else:
      self.is_vertical = False
      self.pos_reached = False
      self.colour = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.is_vertical, _x.pos_reached, _x.colour))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.is_vertical, _x.pos_reached, _x.colour,) = _get_struct_3B().unpack(str[start:end])
      self.is_vertical = bool(self.is_vertical)
      self.pos_reached = bool(self.pos_reached)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.is_vertical, _x.pos_reached, _x.colour))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.is_vertical, _x.pos_reached, _x.colour,) = _get_struct_3B().unpack(str[start:end])
      self.is_vertical = bool(self.is_vertical)
      self.pos_reached = bool(self.pos_reached)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
