// Generated by gencpp from file eurobot2019_messages/drop_status.msg
// DO NOT EDIT!


#ifndef EUROBOT2019_MESSAGES_MESSAGE_DROP_STATUS_H
#define EUROBOT2019_MESSAGES_MESSAGE_DROP_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace eurobot2019_messages
{
template <class ContainerAllocator>
struct drop_status_
{
  typedef drop_status_<ContainerAllocator> Type;

  drop_status_()
    : left_tower_contents(0)
    , middle_tower_contents(0)
    , right_tower_contents(0)  {
    }
  drop_status_(const ContainerAllocator& _alloc)
    : left_tower_contents(0)
    , middle_tower_contents(0)
    , right_tower_contents(0)  {
  (void)_alloc;
    }



   typedef uint8_t _left_tower_contents_type;
  _left_tower_contents_type left_tower_contents;

   typedef uint8_t _middle_tower_contents_type;
  _middle_tower_contents_type middle_tower_contents;

   typedef uint8_t _right_tower_contents_type;
  _right_tower_contents_type right_tower_contents;





  typedef boost::shared_ptr< ::eurobot2019_messages::drop_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eurobot2019_messages::drop_status_<ContainerAllocator> const> ConstPtr;

}; // struct drop_status_

typedef ::eurobot2019_messages::drop_status_<std::allocator<void> > drop_status;

typedef boost::shared_ptr< ::eurobot2019_messages::drop_status > drop_statusPtr;
typedef boost::shared_ptr< ::eurobot2019_messages::drop_status const> drop_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eurobot2019_messages::drop_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eurobot2019_messages::drop_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace eurobot2019_messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'eurobot2019_messages': ['/home/nickick/Eurobot2019/src/eurobot2019_messages/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::eurobot2019_messages::drop_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eurobot2019_messages::drop_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eurobot2019_messages::drop_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eurobot2019_messages::drop_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eurobot2019_messages::drop_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eurobot2019_messages::drop_status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eurobot2019_messages::drop_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86a774b860e3f87b013422373c4196ad";
  }

  static const char* value(const ::eurobot2019_messages::drop_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86a774b860e3f87bULL;
  static const uint64_t static_value2 = 0x013422373c4196adULL;
};

template<class ContainerAllocator>
struct DataType< ::eurobot2019_messages::drop_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eurobot2019_messages/drop_status";
  }

  static const char* value(const ::eurobot2019_messages::drop_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eurobot2019_messages::drop_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The number of pucks in the respective tower\n"
"uint8 left_tower_contents\n"
"uint8 middle_tower_contents\n"
"uint8 right_tower_contents\n"
;
  }

  static const char* value(const ::eurobot2019_messages::drop_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eurobot2019_messages::drop_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_tower_contents);
      stream.next(m.middle_tower_contents);
      stream.next(m.right_tower_contents);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct drop_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eurobot2019_messages::drop_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::eurobot2019_messages::drop_status_<ContainerAllocator>& v)
  {
    s << indent << "left_tower_contents: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_tower_contents);
    s << indent << "middle_tower_contents: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.middle_tower_contents);
    s << indent << "right_tower_contents: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_tower_contents);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EUROBOT2019_MESSAGES_MESSAGE_DROP_STATUS_H
